[package]
name = "todo-actix"
version = "0.1.0"
authors = ["Julio Daniel Reyes <nemesiscodex@gmail.com>"]
edition = "2018"

[features]
default = []

# Integration tests
integration_tests = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-http = "1.0.1"
actix-service = "1.0.5"
futures = "0.3.4"
serde = { version = "1.0.104", features = ["derive"] }
dotenv = "0.15.0"
config = "0.10.1"

# (1) Event-driven, non-blocking platform to
#     write asunchronous applications in rust.
# (2) Actix uses tokio event loop for 
#     the actor system. 
# (3) Bunch of traits and macros to facilitate
#     the mapping from postgres tables to structs
tokio-pg-mapper = "0.1.4"
tokio-pg-mapper-derive = "0.1.4"

deadpool-postgres = "0.5.0"
tokio-postgres = "0.5.1" 


## Error Handlers
slog = "2.5.2"
slog-term = "2.5.0"
slog-async = "2.4.0"
slog-envlogger = "2.2.0"

[dev-dependencies]
lazy_static = "1.4.0"
serde_json = "1.0.48"